### ISSUE TITLE
Minor style issues after docs engine merge

### ISSUE THREAD

**Issue by rogermparent** [iterative/mlem.ai#63]
- [x] Fix misaligned title anchor https://github.com/iterative/mlem.ai/pull/77
![image](https://user-images.githubusercontent.com/9111807/169589938-63a5a665-6def-43ac-9016-edc7d6043cba.png)

- [x] #72 The border line in the content list is missing some margin
<img width="194" alt="image" src="https://user-images.githubusercontent.com/43496356/168840893-81b6b20f-5770-436c-a29e-7e28a12f7a12.png">

- [x] #73 For some reason, the left sidebar is spliing into the content
<img width="892" alt="image" src="https://user-images.githubusercontent.com/43496356/169533862-c6c49072-fa1a-49b0-81c8-7e68fd47f02a.png">

- [x] #74 The github button isn't staying at the top of the page
<img width="752" alt="image" src="https://user-images.githubusercontent.com/43496356/169533319-febe3c95-7c90-4cb3-87d7-a1b261bed57d.png">
